name: psico_app
description: Psico app.

publish_to: 'none'

version: 0.9.0

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Server/Pattern
  get: ^4.7.2
  oauth2: ^2.0.3
  # Utilities
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8
  flutter_easyloading: ^3.0.5
  google_fonts: ^6.2.1
  intl: ^0.20.2
  # Features
  permission_handler: ^12.0.0+1
  flutter_local_notifications: ^19.2.1
  font_awesome_flutter: ^10.8.0
  google_sign_in: ^6.3.0
  fl_chart: ^1.0.0
  cloud_firestore: ^5.6.9
  # Device/App info
  package_info_plus: ^8.3.0
  device_info_plus: ^11.4.0
  connectivity_plus: ^6.1.4
  # Storage
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  # Firebase
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  firebase_crashlytics: ^4.3.7
  firebase_analytics: ^11.5.0
  firebase_performance: ^0.10.1+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  image_path_android: "assets/icon/icon_blank_bg.png"
flutter_native_splash:
  background_image: "assets/images/splash.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/